"""add daily_advice table

Revision ID: 01e0f132969b
Revises: 3053eeb9352f
Create Date: 2026-04-30 13:23:20.514752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01e0f132969b'
down_revision: Union[str, Sequence[str], None] = '3053eeb9352f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_advice',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Owner of this advice record'),
    sa.Column('advice_date', sa.Date(), nullable=False, comment='Date this advice applies to (YYYY-MM-DD)'),
    sa.Column('content', sa.String(length=1000), nullable=False, comment='Personalized advice text'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'advice_date', name='uq_daily_advice_user_date')
    )
    op.create_index(op.f('ix_daily_advice_advice_date'), 'daily_advice', ['advice_date'], unique=False)
    op.create_index('ix_daily_advice_user_date', 'daily_advice', ['user_id', 'advice_date'], unique=False)
    op.create_index(op.f('ix_daily_advice_user_id'), 'daily_advice', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_advice_user_id'), table_name='daily_advice')
    op.drop_index('ix_daily_advice_user_date', table_name='daily_advice')
    op.drop_index(op.f('ix_daily_advice_advice_date'), table_name='daily_advice')
    op.drop_table('daily_advice')
    # ### end Alembic commands ###
